// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJkHxd445dyixNutgtQRH5TuCkGXNoXKo',
    appId: '1:13964355114:web:7173afeef22c6f91d1c553',
    messagingSenderId: '13964355114',
    projectId: 'hazermath',
    authDomain: 'hazermath.firebaseapp.com',
    storageBucket: 'hazermath.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDXyrHH3n3KnXLsC_qX0xF5U4pAb6XQ2g',
    appId: '1:13964355114:android:0dd804b87d2bec71d1c553',
    messagingSenderId: '13964355114',
    projectId: 'hazermath',
    storageBucket: 'hazermath.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALKShWQu7kkYIQ_soM2QrxA-aqeUwnjnE',
    appId: '1:13964355114:ios:a4a7e03640a75ea8d1c553',
    messagingSenderId: '13964355114',
    projectId: 'hazermath',
    storageBucket: 'hazermath.appspot.com',
    iosBundleId: 'com.example.mathProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALKShWQu7kkYIQ_soM2QrxA-aqeUwnjnE',
    appId: '1:13964355114:ios:a4a7e03640a75ea8d1c553',
    messagingSenderId: '13964355114',
    projectId: 'hazermath',
    storageBucket: 'hazermath.appspot.com',
    iosBundleId: 'com.example.mathProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJkHxd445dyixNutgtQRH5TuCkGXNoXKo',
    appId: '1:13964355114:web:f38150f0a27d14c2d1c553',
    messagingSenderId: '13964355114',
    projectId: 'hazermath',
    authDomain: 'hazermath.firebaseapp.com',
    storageBucket: 'hazermath.appspot.com',
  );
}
